
title: Ruixi "Peter" Li
email: pete.ruixi@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Hi, welcome to my page. My name is Ruixi Li, my friends call me Peter or Pete. 
  Learn more about me by exploring the site. 
  Hope you could get a good idea of who I am in the end. Thank you! 
  

baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
instagram_username: petaardation
github_username:  peteruixi

# Build settings
theme: minima
plugins:
  - jekyll-feed

